### ISSUE TITLE
表示のおかしなエンチャント

### ISSUE THREAD

**Issue by knutze** [clamm0363/StoneshardJP#1]
翻訳ありがとうございます。
v1.0422 で表示のおかしなエンチャントを見つけました。

<img width="356" alt="toxicity_resistance" src="https://user-images.githubusercontent.com/34371397/80194930-1c665780-8656-11ea-9ecc-2e6d83185329.png">

見つけたものをリストアップ（アルファベット順）します。

* Armor_Damage
* Bleeding_Resistance
* Bodypart_Damage
* Daze_Chance
* Knockback_Chance
* Pain_Resistance
* Physical_Resistance
* Stun_Chance
* Toxicity_Resistance

**Comment by knutze** [comment]
<img width="355" alt="armor_damage" src="https://user-images.githubusercontent.com/34371397/80204469-e5973e00-8663-11ea-8b2e-b34e61ba407b.png">

**Comment by knutze** [comment]
<img width="357" alt="pain_resistance" src="https://user-images.githubusercontent.com/34371397/80205067-fac09c80-8664-11ea-9015-b0e689ec7b21.png">

**Comment by clamm0363** [comment]
報告ありがとうございます。その問題は把握しておりまして、根本的な原因はゲーム側に "Pain_Resistance" 等のlocalization keyが用意されていないことにあります。
次回更新にて日本語化ファイル独自でキーを用意してこの表示が正常になるようにします（すでに動作確認は終えています）ので、今しばらくお待ちください。

**Comment by clamm0363** [comment]
しかし、私も独自に調査していたのですが、挙げていただいたスクショのキーは初めて見ました。かなり多くの種類のエンチャントにキーが用意されていないようですね…

**Comment by knutze** [comment]
そうでしたか。
まだあるのですが、追記するのとしないのとどちらがが良いでしょうか？

**Comment by clamm0363** [comment]
画像のキーの部分、 "Pain_Resistance" 等の部分ですね。それだけを列記していただくことは可能でしょうか？

**Comment by knutze** [comment]
了解です

**Comment by clamm0363** [comment]
あ、最初の投稿に追記していただいてたのですね…
全く気が付いておらず申し訳ございません。挙げていただいたキーは翻訳を入力して
正常に表示されるようにしておきます。ありがとうございました！

**Comment by clamm0363** [comment]
私の調査と合わせて、現在のところ次のキーがゲーム本体に存在しません

Stun_Resistance
Knockback_Resistance
Bleeding_Resistance
Magic_Resistance
Nature_Resistance
Physical_Resistance
Hunger_Resistance
Pain_Resistance
Toxicity_Resistance
Cooldown_Reduction
Daze_Chance
Knockback_Chance
Stun_Chance
Armor_Damage
Bodypart_Damage

**Comment by knutze** [comment]
対応ありがとうございます！

**Comment by knutze** [comment]
Pain_Resistance が「鋲付きの」になっているのは意図通りでしょうか？
翻訳内容に意見するつもりはありません。対応前に見た記憶がある他のエンチャントと同じ名前の気がしたので、記憶違いかもしれませんが念の為ご連絡しておこうと思った次第です。

**Comment by clamm0363** [comment]
はいそうです。本体側で名称があってキーが設定されていない接頭辞がいくつかあり、
いくつかの物には流用していますが、効果内容と名称に違和感があるかもしれません。
本体側のアップデートで修正される部分だと思いますので、ここは暫定的に設定されている、と考えていただいた方がいいと思います。
